th main.lua -nGPU 4 -nDonkeys 8 -cropSize 224 -batchSize 128 -nClasses 257\
            -data /media/SuperSSD/spk/257/257OriTest257Ori\
            -cache /media/HDD1/spk/257/checkpoints/fine\
            -optimizer adam \
            -regimes adam \
            -netType faceBook\
            -index res18\
            -epochSize 120\
            -nEpochs 100\
            -retrain /media/HDD1/spk/model/resnet/resnet-18.t7\
            -rpLastlayer
